# Modified from https://github.com/lightbend/kalix-jvm-sdk/blob/main/samples/scala-protobuf-customer-registry-quickstart/docker-compose.yml
version: "3"
services:
  kalix-proxy-scheduled-tasks:
    image: gcr.io/kalix-public/kalix-proxy:1.1.21
    container_name: kalix-proxy-scheduled-tasks
    ports:
      - "9010:9010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dkalix.dev-mode.service-port-mappings.scheduled-tasks=host.docker.internal:9010
        -Dkalix.dev-mode.service-port-mappings.bounded-context=host.docker.internal:9001
        -Dconfig.resource=integration-test.conf
        -Dlogback.configurationFile=logback-dev-mode.xml
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8083}
      HTTP_PORT: 9010
      ACL_ENABLED: 'false'
