package com.improving.extensions.oidc.impl

import com.google.protobuf.empty.Empty
import kalix.scalasdk.replicatedentity.{ReplicatedEntity, ReplicatedRegisterMap, ReplicatedRegisterMapEntity}

// This code was generated by Kalix tooling.
// DO NOT EDIT.

abstract private[impl] class AbstractReplicatedSessionStoreEntity
    extends ReplicatedRegisterMapEntity[String, SessionData] {

  def putSession(
    currentData: ReplicatedRegisterMap[String, SessionData],
    storeSessionRequest: StoreSessionRequest
  ): ReplicatedEntity.Effect[Empty]

  def getSession(
    currentData: ReplicatedRegisterMap[String, SessionData],
    sessionKey: SessionKey
  ): ReplicatedEntity.Effect[GetSessionResponse]

}
