// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.improving.extensions.oidc.impl

import com.google.protobuf.{ByteString => ProtobufByteString}
import scalapb._

@SerialVersionUID(0L)
final case class SessionData(
  data: ProtobufByteString = ProtobufByteString.EMPTY,
  unknownFields: UnknownFieldSet = UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[SessionData] {

  @transient private[this] var serializedSizeMemoized: Int = 0

  private[this] def computeSerializedSize(): Int = {
    var size = 0

    {
      val value = data
      if (!value.isEmpty) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, value)
      }
    };
    size += unknownFields.serializedSize
    size
  }

  override def serializedSize: Int = {
    var size = serializedSizeMemoized
    if (size == 0) {
      size = computeSerializedSize() + 1
      serializedSizeMemoized = size
    }
    size - 1

  }

  def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
    {
      val v = data
      if (!v.isEmpty) {
        output.writeBytes(2, v)
      }
    }
    unknownFields.writeTo(output)
  }

  def withData(pbs: ProtobufByteString): SessionData = copy(data = pbs)

  def withUnknownFields(ufs: UnknownFieldSet): SessionData = copy(unknownFields = ufs)

  def discardUnknownFields: SessionData = copy(unknownFields = UnknownFieldSet.empty)

  def getFieldByNumber(fieldNumber: Int): Any = {
    (fieldNumber: @ unchecked) match {
      case 2 =>
        val t = data
        if (t != ProtobufByteString.EMPTY) t else null
    }
  }

  def getField(field: descriptors.FieldDescriptor): descriptors.PValue = {
    Predef.require(field.containingMessage eq companion.scalaDescriptor)
    (field.number: @ unchecked) match {
      case 2 => descriptors.PByteString(data)
    }
  }

  def toProtoString: Predef.String = TextFormat.printToUnicodeString(this)

  def companion: SessionData.type = SessionData
}

object SessionData extends scalapb.GeneratedMessageCompanion[SessionData] {

  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[SessionData] = this

  def parseFrom(input: com.google.protobuf.CodedInputStream): SessionData = {
    var data: ProtobufByteString               = ProtobufByteString.EMPTY
    var unknownFields : UnknownFieldSet.Builder = null
    var done                                                     = false
    while (!done) {
      val tag = input.readTag()
      tag match {
        case 0   => done = true
        case 18  =>
          data = input.readBytes()
        case tag =>
          if (unknownFields == null) {
            unknownFields = new UnknownFieldSet.Builder()
          }
          unknownFields.parseField(tag, input)
      }
    }
    SessionData(
      data = data,
      unknownFields = if (unknownFields == null) UnknownFieldSet.empty else unknownFields.result()
    )
  }

  implicit def messageReads: descriptors.Reads[SessionData] = descriptors.Reads {
    case descriptors.PMessage(fieldsMap) =>
      Predef.require(
        fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      SessionData(
        data = fieldsMap
          .get(scalaDescriptor.findFieldByNumber(2).get)
          .map(_.as[ProtobufByteString])
          .getOrElse(ProtobufByteString.EMPTY)
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(0)

  def scalaDescriptor: descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(0)

  def messageCompanionForFieldNumber(number: Int): GeneratedMessageCompanion[_] =
    throw new MatchError(number)

  lazy val nestedMessagesCompanions
    : Seq[GeneratedMessageCompanion[_ <: GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(fieldNumber: Int): GeneratedEnumCompanion[_] =
    throw new MatchError(fieldNumber)

  lazy val defaultInstance: SessionData = SessionData(
    data = ProtobufByteString.EMPTY
  )

  implicit class SessionDataLens[UpperPB](_l: lenses.Lens[UpperPB, SessionData])
      extends lenses.ObjectLens[UpperPB, SessionData](_l) {

    def data: lenses.Lens[UpperPB, ProtobufByteString] =
      field(_.data)((c_, f_) => c_.copy(data = f_))

  }

  final val DATA_FIELD_NUMBER = 2

  def of(data: ProtobufByteString): SessionData = SessionData(data)
}

@SerialVersionUID(0L)
final case class SessionKey(
  entityId: Predef.String,
  key: Predef.String,
  unknownFields: UnknownFieldSet = UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[SessionKey] {

  @transient private[this] var serializedSizeMemoized: Int = 0

  private[this] def computeSerializedSize(): Int = {
    var size = 0

    {
      val value = entityId
      if (value.nonEmpty) {
        size += com.google.protobuf.CodedOutputStream.computeStringSize(1, value)
      }
    };

    {
      val value = key
      if (value.nonEmpty) {
        size += com.google.protobuf.CodedOutputStream.computeStringSize(2, value)
      }
    };
    size += unknownFields.serializedSize
    size
  }

  override def serializedSize: Int = {
    var size = serializedSizeMemoized
    if (size == 0) {
      size = computeSerializedSize() + 1
      serializedSizeMemoized = size
    }
    size - 1

  }

  def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
    {
      val v = entityId
      if (v.nonEmpty) {
        output.writeString(1, v)
      }
    };
    {
      val v = key
      if (v.nonEmpty) {
        output.writeString(2, v)
      }
    };
    unknownFields.writeTo(output)
  }

  def withEntityId(v: Predef.String): SessionKey = copy(entityId = v)

  def withKey(v: Predef.String): SessionKey = copy(key = v)

  def withUnknownFields(v: UnknownFieldSet): SessionKey = copy(unknownFields = v)

  def discardUnknownFields: SessionKey = copy(unknownFields = UnknownFieldSet.empty)

  def getFieldByNumber(fieldNumber: Int): Any = {
    (fieldNumber: @ unchecked) match {
      case 1 =>
        val t = entityId
        if (t != "") t else null
      case 2 =>
        val t = key
        if (t != "") t else null
    }
  }

  def getField(field: descriptors.FieldDescriptor): descriptors.PValue = {
    Predef.require(field.containingMessage eq companion.scalaDescriptor)
    (field.number: @ unchecked) match {
      case 1 => descriptors.PString(entityId)
      case 2 => descriptors.PString(key)
    }
  }

  def toProtoString: Predef.String = TextFormat.printToUnicodeString(this)

  def companion: SessionKey.type = SessionKey
}

object SessionKey extends scalapb.GeneratedMessageCompanion[SessionKey] {

  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[SessionKey] = this

  def parseFrom(input: com.google.protobuf.CodedInputStream): SessionKey = {
    var entityId: Predef.String                      = ""
    var key: Predef.String                           = ""
    var unknownFields : UnknownFieldSet.Builder = null
    var done                                                     = false
    while (!done) {
      val tag = input.readTag()
      tag match {
        case 0   => done = true
        case 10  =>
          entityId = input.readStringRequireUtf8()
        case 18  =>
          key = input.readStringRequireUtf8()
        case tag =>
          if (unknownFields == null) {
            unknownFields = new UnknownFieldSet.Builder()
          }
          unknownFields.parseField(tag, input)
      }
    }
    SessionKey(
      entityId = entityId,
      key = key,
      unknownFields = if (unknownFields == null) UnknownFieldSet.empty else unknownFields.result()
    )
  }

  implicit def messageReads: descriptors.Reads[SessionKey] = descriptors.Reads {
    case descriptors.PMessage(fieldsMap) =>
      Predef.require(
        fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      SessionKey(
        entityId =
          fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[Predef.String]).getOrElse(""),
        key =
          fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[Predef.String]).getOrElse("")
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(1)

  def scalaDescriptor: descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(1)

  def messageCompanionForFieldNumber(number: Int): GeneratedMessageCompanion[_] =
    throw new MatchError(number)

  lazy val nestedMessagesCompanions
    : Seq[GeneratedMessageCompanion[_ <: GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(fieldNumber: Int): GeneratedEnumCompanion[_] =
    throw new MatchError(fieldNumber)

  lazy val defaultInstance: SessionKey = SessionKey(
    entityId = "",
    key = ""
  )

  implicit class SessionKeyLens[UpperPB](_l: lenses.Lens[UpperPB, SessionKey])
      extends lenses.ObjectLens[UpperPB, SessionKey](_l) {

    def entityId: lenses.Lens[UpperPB, Predef.String] =
      field(_.entityId)((c_, f_) => c_.copy(entityId = f_))

    def key: lenses.Lens[UpperPB, Predef.String] =
      field(_.key)((c_, f_) => c_.copy(key = f_))

  }

  final val ENTITY_ID_FIELD_NUMBER = 1
  final val KEY_FIELD_NUMBER       = 2

  def of(entityId: Predef.String, key: Predef.String): SessionKey =
    SessionKey(entityId, key)

}

@SerialVersionUID(0L)
final case class StoreSessionRequest(
  entityId: Predef.String,
  key: Predef.String,
  data: ProtobufByteString = ProtobufByteString.EMPTY,
  unknownFields: UnknownFieldSet = UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[StoreSessionRequest] {

  @transient private[this] var serializedSizeMemoized: Int = 0

  private[this] def computeSerializedSize(): Int = {
    var size = 0

    {
      val value = entityId
      if (value.nonEmpty) {
        size += com.google.protobuf.CodedOutputStream.computeStringSize(1, value)
      }
    };

    {
      val value = key
      if (value.nonEmpty) {
        size += com.google.protobuf.CodedOutputStream.computeStringSize(2, value)
      }
    };

    {
      val value = data
      if (!value.isEmpty) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, value)
      }
    };
    size += unknownFields.serializedSize
    size
  }

  override def serializedSize: Int = {
    var size = serializedSizeMemoized
    if (size == 0) {
      size = computeSerializedSize() + 1
      serializedSizeMemoized = size
    }
    size - 1

  }

  def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
    {
      val v = entityId
      if (v.nonEmpty) {
        output.writeString(1, v)
      }
    };
    {
      val v = key
      if (v.nonEmpty) {
        output.writeString(2, v)
      }
    };
    {
      val v = data
      if (!v.isEmpty) {
        output.writeBytes(3, v)
      }
    };
    unknownFields.writeTo(output)
  }

  def withEntityId(v: Predef.String): StoreSessionRequest = copy(entityId = v)

  def withKey(v: Predef.String): StoreSessionRequest = copy(key = v)

  def withData(v: ProtobufByteString): StoreSessionRequest = copy(data = v)

  def withUnknownFields(v: UnknownFieldSet): StoreSessionRequest = copy(unknownFields = v)

  def discardUnknownFields: StoreSessionRequest = copy(unknownFields = UnknownFieldSet.empty)

  def getFieldByNumber(fieldNumber: Int): Any = {
    (fieldNumber: @ unchecked) match {
      case 1 =>
        val t = entityId
        if (t != "") t else null
      case 2 =>
        val t = key
        if (t != "") t else null
      case 3 =>
        val t = data
        if (t != ProtobufByteString.EMPTY) t else null
    }
  }

  def getField(field: descriptors.FieldDescriptor): descriptors.PValue = {
    Predef.require(field.containingMessage eq companion.scalaDescriptor)
    (field.number: @ unchecked) match {
      case 1 => descriptors.PString(entityId)
      case 2 => descriptors.PString(key)
      case 3 => descriptors.PByteString(data)
    }
  }

  def toProtoString: Predef.String = TextFormat.printToUnicodeString(this)

  def companion: StoreSessionRequest.type = StoreSessionRequest
}

object StoreSessionRequest extends scalapb.GeneratedMessageCompanion[StoreSessionRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[StoreSessionRequest] = this

  def parseFrom(input: com.google.protobuf.CodedInputStream): StoreSessionRequest = {
    var entityId: Predef.String                      = ""
    var key: Predef.String                           = ""
    var data: ProtobufByteString                     = ProtobufByteString.EMPTY
    var unknownFields : UnknownFieldSet.Builder      = null
    var done                                         = false
    while (!done) {
      val tag = input.readTag()
      tag match {
        case 0   => done = true
        case 10  =>
          entityId = input.readStringRequireUtf8()
        case 18  =>
          key = input.readStringRequireUtf8()
        case 26  =>
          data = input.readBytes()
        case tag =>
          if (unknownFields == null) {
            unknownFields = new UnknownFieldSet.Builder()
          }
          unknownFields.parseField(tag, input)
      }
    }
    StoreSessionRequest(
      entityId = entityId,
      key = key,
      data = data,
      unknownFields = if (unknownFields == null) UnknownFieldSet.empty else unknownFields.result()
    )
  }

  implicit def messageReads: descriptors.Reads[StoreSessionRequest] = descriptors.Reads {
    case descriptors.PMessage(fieldsMap) =>
      Predef.require(
        fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      StoreSessionRequest(
        entityId =
          fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[Predef.String]).getOrElse(""),
        key =
          fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[Predef.String]).getOrElse(""),
        data = fieldsMap
          .get(scalaDescriptor.findFieldByNumber(3).get)
          .map(_.as[ProtobufByteString])
          .getOrElse(ProtobufByteString.EMPTY)
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(2)

  def scalaDescriptor: descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(2)

  def messageCompanionForFieldNumber(number: Int): GeneratedMessageCompanion[_] =
    throw new MatchError(number)

  lazy val nestedMessagesCompanions
    : Seq[GeneratedMessageCompanion[_ <: GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(fieldNumber: Int): GeneratedEnumCompanion[_] =
    throw new MatchError(fieldNumber)

  lazy val defaultInstance: StoreSessionRequest = StoreSessionRequest(
    entityId = "",
    key = "",
    data = ProtobufByteString.EMPTY
  )

  implicit class StoreSessionRequestLens[UpperPB](_l: lenses.Lens[UpperPB, StoreSessionRequest])
      extends lenses.ObjectLens[UpperPB, StoreSessionRequest](_l) {

    def entityId: lenses.Lens[UpperPB, Predef.String] =
      field(_.entityId)((c_, f_) => c_.copy(entityId = f_))

    def key: lenses.Lens[UpperPB, Predef.String] =
      field(_.key)((c_, f_) => c_.copy(key = f_))

    def data: lenses.Lens[UpperPB, ProtobufByteString] =
      field(_.data)((c_, f_) => c_.copy(data = f_))

  }

  final val ENTITY_ID_FIELD_NUMBER = 1
  final val KEY_FIELD_NUMBER       = 2
  final val DATA_FIELD_NUMBER      = 3

  def of(
    entityId: Predef.String,
    key: Predef.String,
    data: ProtobufByteString
  ): StoreSessionRequest =
    StoreSessionRequest(entityId, key, data)

}

@SerialVersionUID(0L)
final case class GetSessionResponse(
  session: scala.Option[SessionData] = None,
  unknownFields: scalapb.UnknownFieldSet = scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[GetSessionResponse] {

  @transient
  private[this] var serializedSizeMemoized: Int = 0

  private[this] def computeSerializedSize(): Int = {
    var size = 0
    if (session.isDefined) {
      val value = session.get
      size += 1 + com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(value.serializedSize) + value.serializedSize
    };
    size += unknownFields.serializedSize
    size
  }

  override def serializedSize: Int = {
    var size = serializedSizeMemoized
    if (size == 0) {
      size = computeSerializedSize() + 1
      serializedSizeMemoized = size
    }
    size - 1

  }

  def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
    session.foreach { v =>
      val m = v
      output.writeTag(1, 2)
      output.writeUInt32NoTag(m.serializedSize)
      m.writeTo(output)
    };
    unknownFields.writeTo(output)
  }

  def getSession: SessionData = session.getOrElse(SessionData.defaultInstance)

  def clearSession: GetSessionResponse = copy(session = None)

  def withSession(v: SessionData): GetSessionResponse = copy(session = Option(v))

  def withUnknownFields(v: UnknownFieldSet): GetSessionResponse = copy(unknownFields = v)

  def discardUnknownFields: GetSessionResponse = copy(unknownFields = UnknownFieldSet.empty)

  def getFieldByNumber(fieldNumber: Int): Any = {
    (fieldNumber: @ unchecked) match {
      case 1 => session.orNull
    }
  }

  def getField(field: descriptors.FieldDescriptor): descriptors.PValue = {
    Predef.require(field.containingMessage eq companion.scalaDescriptor)
    (field.number: @ unchecked) match {
      case 1 => session.map(_.toPMessage).getOrElse(descriptors.PEmpty)
    }
  }

  def toProtoString: Predef.String = TextFormat.printToUnicodeString(this)

  def companion: GetSessionResponse.type = GetSessionResponse

}

object GetSessionResponse extends scalapb.GeneratedMessageCompanion[GetSessionResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[GetSessionResponse] = this

  def parseFrom(input: com.google.protobuf.CodedInputStream): GetSessionResponse = {
    var session: Option[SessionData]                 = None
    var unknownFields : UnknownFieldSet.Builder = null
    var done                                                     = false
    while (!done) {
      val tag = input.readTag()
      tag match {
        case 0   => done = true
        case 10  =>
          session = Option(
            session.fold(LiteParser.readMessage[SessionData](input))(
              LiteParser.readMessage(input, _)
            )
          )
        case tag =>
          if (unknownFields == null) {
            unknownFields = new UnknownFieldSet.Builder()
          }
          unknownFields.parseField(tag, input)
      }
    }
    GetSessionResponse(
      session = session,
      unknownFields = if (unknownFields == null) UnknownFieldSet.empty else unknownFields.result()
    )
  }

  implicit def messageReads: descriptors.Reads[GetSessionResponse] = descriptors.Reads {
    case descriptors.PMessage(fieldsMap) =>
      Predef.require(
        fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      GetSessionResponse(
        session =
          fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[Option[SessionData]])
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(3)

  def scalaDescriptor: descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(3)

  def messageCompanionForFieldNumber(number: Int): GeneratedMessageCompanion[_] = {
    var out: GeneratedMessageCompanion[_] = null
    (number: @ unchecked) match {
      case 1 => out = SessionData
    }
    out
  }

  lazy val nestedMessagesCompanions
    : Seq[GeneratedMessageCompanion[_ <: GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(fieldNumber: Int): GeneratedEnumCompanion[_] =
    throw new MatchError(fieldNumber)

  lazy val defaultInstance: GetSessionResponse = GetSessionResponse(session = None)

  implicit class GetSessionResponseLens[UpperPB](_l: lenses.Lens[UpperPB, GetSessionResponse])
      extends lenses.ObjectLens[UpperPB, GetSessionResponse](_l) {

    def session: lenses.Lens[UpperPB, SessionData] =
      field(_.getSession)((c_, f_) => c_.copy(session = Option(f_)))

    def optionalSession: lenses.Lens[UpperPB, scala.Option[SessionData]] =
      field(_.session)((c_, f_) => c_.copy(session = f_))

  }

  final val SESSION_FIELD_NUMBER = 1

  def of(session: scala.Option[SessionData]): GetSessionResponse = GetSessionResponse(session)

}

object ReplicatedSessionStoreProto extends GeneratedFileObject {

  lazy val dependencies: Seq[GeneratedFileObject] = Seq(
    com.google.protobuf.empty.EmptyProto,
    kalix.AnnotationsProto,
    scalapb.options.ScalapbProto
  )

  lazy val messagesCompanions: Seq[GeneratedMessageCompanion[_ <: GeneratedMessage]] =
    Seq[GeneratedMessageCompanion[_ <: GeneratedMessage]](
      SessionData,
      SessionKey,
      StoreSessionRequest,
      GetSessionResponse
    )

  private lazy val ProtoBytes: Array[Byte] =
    scalapb.Encoding.fromBase64(
      scala.collection.immutable
        .Seq(
          """CkFjb20vZXhhbXBsZS9ib3VuZGVkLWNvbnRleHQvZW50aXR5L3JlcGxpY2F0ZWRfc2Vzc2lvbl9zdG9yZS5wcm90bxIiY29tL
  mltcHJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbBobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGhdrYWxpeC9hbm5vdGF0a
  W9ucy5wcm90bxoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIiwKC1Nlc3Npb25EYXRhEh0KBGRhdGEYAiABKAxCCeI/BhIEZGF0YVIEZ
  GF0YSJZCgpTZXNzaW9uS2V5Ei8KCWVudGl0eV9pZBgBIAEoCUIS4j8KEghlbnRpdHlJZMJDAggBUghlbnRpdHlJZBIaCgNrZXkYA
  iABKAlCCOI/BRIDa2V5UgNrZXkigQEKE1N0b3JlU2Vzc2lvblJlcXVlc3QSLwoJZW50aXR5X2lkGAEgASgJQhLiPwoSCGVudGl0e
  UlkwkMCCAFSCGVudGl0eUlkEhoKA2tleRgCIAEoCUII4j8FEgNrZXlSA2tleRIdCgRkYXRhGAMgASgMQgniPwYSBGRhdGFSBGRhd
  GEibQoSR2V0U2Vzc2lvblJlc3BvbnNlElcKB3Nlc3Npb24YASABKAsyLy5jb20uaW1wcm92aW5nLmV4dGVuc2lvbnMub2lkYy5pb
  XBsLlNlc3Npb25EYXRhQgziPwkSB3Nlc3Npb25SB3Nlc3Npb24yjAMKFlJlcGxpY2F0ZWRTZXNzaW9uU3RvcmUSXQoKUHV0U2Vzc
  2lvbhI3LmNvbS5pbXByb3ZpbmcuZXh0ZW5zaW9ucy5vaWRjLmltcGwuU3RvcmVTZXNzaW9uUmVxdWVzdBoWLmdvb2dsZS5wcm90b
  2J1Zi5FbXB0eRJ0CgpHZXRTZXNzaW9uEi4uY29tLmltcHJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbC5TZXNzaW9uS2V5GjYuY
  29tLmltcHJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbC5HZXRTZXNzaW9uUmVzcG9uc2UanAHKQ5gBGpUBCj9jb20uaW1wcm92a
  W5nLmV4dGVuc2lvbnMub2lkYy5pbXBsLlJlcGxpY2F0ZWRTZXNzaW9uU3RvcmVFbnRpdHkSGHJlcGxpY2F0ZWQtc2Vzc2lvbi1zd
  G9yZUI4CgZzdHJpbmcSLmNvbS5pbXByb3ZpbmcuZXh0ZW5zaW9ucy5vaWRjLmltcGwuU2Vzc2lvbkRhdGFCMOI/LQoiY29tLmltc
  HJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbBABKAFYALgBAGIGcHJvdG8z"""
        )
        .mkString
    )

  lazy val scalaDescriptor: descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }

  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(
      javaProto,
      Array(
        com.google.protobuf.empty.EmptyProto.javaDescriptor,
        kalix.AnnotationsProto.javaDescriptor,
        scalapb.options.ScalapbProto.javaDescriptor
      )
    )
  }

  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor

}
