// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.improving.extensions.oidc.impl

@SerialVersionUID(0L)
final case class SessionData(
  data: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
  unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[SessionData] {

  @transient private[this] var __serializedSizeMemoized: _root_.scala.Int = 0

  private[this] def __computeSerializedSize(): _root_.scala.Int = {
    var __size = 0

    {
      val __value = data
      if (!__value.isEmpty) {
        __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
      }
    };
    __size += unknownFields.serializedSize
    __size
  }

  override def serializedSize: _root_.scala.Int = {
    var __size = __serializedSizeMemoized
    if (__size == 0) {
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    }
    __size - 1

  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    {
      val __v = data
      if (!__v.isEmpty) {
        _output__.writeBytes(2, __v)
      }
    }
    unknownFields.writeTo(_output__)
  }

  def withData(__v: _root_.com.google.protobuf.ByteString): SessionData = copy(data = __v)

  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet): SessionData = copy(unknownFields = __v)

  def discardUnknownFields: SessionData = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 2 => {
        val __t = data
        if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
      }
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 2 => _root_.scalapb.descriptors.PByteString(data)
    }
  }

  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion: SessionData.type = SessionData
}

object SessionData extends scalapb.GeneratedMessageCompanion[SessionData] {

  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[SessionData] = this

  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): SessionData = {
    var __data: _root_.com.google.protobuf.ByteString               = _root_.com.google.protobuf.ByteString.EMPTY
    var `_unknownFields__` : _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__                                                     = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0   => _done__ = true
        case 18  =>
          __data = _input__.readBytes()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    SessionData(
      data = __data,
      unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }

  implicit def messageReads: _root_.scalapb.descriptors.Reads[SessionData] = _root_.scalapb.descriptors.Reads {
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(
        __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      SessionData(
        data = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(2).get)
          .map(_.as[_root_.com.google.protobuf.ByteString])
          .getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(0)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(0)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] =
    throw new MatchError(__number)

  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] =
    throw new MatchError(__fieldNumber)

  lazy val defaultInstance: SessionData = SessionData(
    data = _root_.com.google.protobuf.ByteString.EMPTY
  )

  implicit class SessionDataLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, SessionData])
      extends _root_.scalapb.lenses.ObjectLens[UpperPB, SessionData](_l) {

    def data: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] =
      field(_.data)((c_, f_) => c_.copy(data = f_))

  }

  final val DATA_FIELD_NUMBER = 2

  def of(data: _root_.com.google.protobuf.ByteString): SessionData = SessionData(data)
}

@SerialVersionUID(0L)
final case class SessionKey(
  entityId: _root_.scala.Predef.String,
  key: _root_.scala.Predef.String,
  unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[SessionKey] {

  @transient private[this] var __serializedSizeMemoized: _root_.scala.Int = 0

  private[this] def __computeSerializedSize(): _root_.scala.Int = {
    var __size = 0

    {
      val __value = entityId
      if (__value.nonEmpty) {
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
      }
    };

    {
      val __value = key
      if (__value.nonEmpty) {
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
      }
    };
    __size += unknownFields.serializedSize
    __size
  }

  override def serializedSize: _root_.scala.Int = {
    var __size = __serializedSizeMemoized
    if (__size == 0) {
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    }
    __size - 1

  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    {
      val __v = entityId
      if (__v.nonEmpty) {
        _output__.writeString(1, __v)
      }
    };
    {
      val __v = key
      if (__v.nonEmpty) {
        _output__.writeString(2, __v)
      }
    };
    unknownFields.writeTo(_output__)
  }

  def withEntityId(__v: _root_.scala.Predef.String): SessionKey = copy(entityId = __v)

  def withKey(__v: _root_.scala.Predef.String): SessionKey = copy(key = __v)

  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet): SessionKey = copy(unknownFields = __v)

  def discardUnknownFields: SessionKey = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 1 => {
        val __t = entityId
        if (__t != "") __t else null
      }
      case 2 => {
        val __t = key
        if (__t != "") __t else null
      }
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 1 => _root_.scalapb.descriptors.PString(entityId)
      case 2 => _root_.scalapb.descriptors.PString(key)
    }
  }

  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion: SessionKey.type = SessionKey
}

object SessionKey extends scalapb.GeneratedMessageCompanion[SessionKey] {

  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[SessionKey] = this

  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): SessionKey = {
    var __entityId: _root_.scala.Predef.String                      = ""
    var __key: _root_.scala.Predef.String                           = ""
    var `_unknownFields__` : _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__                                                     = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0   => _done__ = true
        case 10  =>
          __entityId = _input__.readStringRequireUtf8()
        case 18  =>
          __key = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    SessionKey(
      entityId = __entityId,
      key = __key,
      unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }

  implicit def messageReads: _root_.scalapb.descriptors.Reads[SessionKey] = _root_.scalapb.descriptors.Reads {
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(
        __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      SessionKey(
        entityId =
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        key =
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(1)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(1)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] =
    throw new MatchError(__number)

  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] =
    throw new MatchError(__fieldNumber)

  lazy val defaultInstance: SessionKey = SessionKey(
    entityId = "",
    key = ""
  )

  implicit class SessionKeyLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, SessionKey])
      extends _root_.scalapb.lenses.ObjectLens[UpperPB, SessionKey](_l) {

    def entityId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] =
      field(_.entityId)((c_, f_) => c_.copy(entityId = f_))

    def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] =
      field(_.key)((c_, f_) => c_.copy(key = f_))

  }

  final val ENTITY_ID_FIELD_NUMBER = 1
  final val KEY_FIELD_NUMBER       = 2

  def of(entityId: _root_.scala.Predef.String, key: _root_.scala.Predef.String): SessionKey =
    SessionKey(entityId, key)

}

@SerialVersionUID(0L)
final case class StoreSessionRequest(
  entityId: _root_.scala.Predef.String,
  key: _root_.scala.Predef.String,
  data: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
  unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[StoreSessionRequest] {

  @transient private[this] var __serializedSizeMemoized: _root_.scala.Int = 0

  private[this] def __computeSerializedSize(): _root_.scala.Int = {
    var __size = 0

    {
      val __value = entityId
      if (__value.nonEmpty) {
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
      }
    };

    {
      val __value = key
      if (__value.nonEmpty) {
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
      }
    };

    {
      val __value = data
      if (!__value.isEmpty) {
        __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(3, __value)
      }
    };
    __size += unknownFields.serializedSize
    __size
  }

  override def serializedSize: _root_.scala.Int = {
    var __size = __serializedSizeMemoized
    if (__size == 0) {
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    }
    __size - 1

  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    {
      val __v = entityId
      if (__v.nonEmpty) {
        _output__.writeString(1, __v)
      }
    };
    {
      val __v = key
      if (__v.nonEmpty) {
        _output__.writeString(2, __v)
      }
    };
    {
      val __v = data
      if (!__v.isEmpty) {
        _output__.writeBytes(3, __v)
      }
    };
    unknownFields.writeTo(_output__)
  }

  def withEntityId(__v: _root_.scala.Predef.String): StoreSessionRequest = copy(entityId = __v)

  def withKey(__v: _root_.scala.Predef.String): StoreSessionRequest = copy(key = __v)

  def withData(__v: _root_.com.google.protobuf.ByteString): StoreSessionRequest = copy(data = __v)

  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet): StoreSessionRequest = copy(unknownFields = __v)

  def discardUnknownFields: StoreSessionRequest = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 1 => {
        val __t = entityId
        if (__t != "") __t else null
      }
      case 2 => {
        val __t = key
        if (__t != "") __t else null
      }
      case 3 => {
        val __t = data
        if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
      }
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 1 => _root_.scalapb.descriptors.PString(entityId)
      case 2 => _root_.scalapb.descriptors.PString(key)
      case 3 => _root_.scalapb.descriptors.PByteString(data)
    }
  }

  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion: StoreSessionRequest.type = StoreSessionRequest
}

object StoreSessionRequest extends scalapb.GeneratedMessageCompanion[StoreSessionRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[StoreSessionRequest] = this

  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): StoreSessionRequest = {
    var __entityId: _root_.scala.Predef.String                      = ""
    var __key: _root_.scala.Predef.String                           = ""
    var __data: _root_.com.google.protobuf.ByteString               = _root_.com.google.protobuf.ByteString.EMPTY
    var `_unknownFields__` : _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__                                                     = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0   => _done__ = true
        case 10  =>
          __entityId = _input__.readStringRequireUtf8()
        case 18  =>
          __key = _input__.readStringRequireUtf8()
        case 26  =>
          __data = _input__.readBytes()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    StoreSessionRequest(
      entityId = __entityId,
      key = __key,
      data = __data,
      unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }

  implicit def messageReads: _root_.scalapb.descriptors.Reads[StoreSessionRequest] = _root_.scalapb.descriptors.Reads {
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(
        __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      StoreSessionRequest(
        entityId =
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        key =
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        data = __fieldsMap
          .get(scalaDescriptor.findFieldByNumber(3).get)
          .map(_.as[_root_.com.google.protobuf.ByteString])
          .getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(2)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(2)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] =
    throw new MatchError(__number)

  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] =
    throw new MatchError(__fieldNumber)

  lazy val defaultInstance: StoreSessionRequest = StoreSessionRequest(
    entityId = "",
    key = "",
    data = _root_.com.google.protobuf.ByteString.EMPTY
  )

  implicit class StoreSessionRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, StoreSessionRequest])
      extends _root_.scalapb.lenses.ObjectLens[UpperPB, StoreSessionRequest](_l) {

    def entityId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] =
      field(_.entityId)((c_, f_) => c_.copy(entityId = f_))

    def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] =
      field(_.key)((c_, f_) => c_.copy(key = f_))

    def data: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] =
      field(_.data)((c_, f_) => c_.copy(data = f_))

  }

  final val ENTITY_ID_FIELD_NUMBER = 1
  final val KEY_FIELD_NUMBER       = 2
  final val DATA_FIELD_NUMBER      = 3

  def of(
    entityId: _root_.scala.Predef.String,
    key: _root_.scala.Predef.String,
    data: _root_.com.google.protobuf.ByteString
  ): StoreSessionRequest =
    StoreSessionRequest(entityId, key, data)

}

@SerialVersionUID(0L)
final case class GetSessionResponse(
  session: scala.Option[SessionData] = _root_.scala.None,
  unknownFields: scalapb.UnknownFieldSet = scalapb.UnknownFieldSet.empty
) extends scalapb.GeneratedMessage
    with scalapb.lenses.Updatable[GetSessionResponse] {

  @transient
  private[this] var __serializedSizeMemoized: _root_.scala.Int = 0

  private[this] def __computeSerializedSize(): _root_.scala.Int = {
    var __size = 0
    if (session.isDefined) {
      val __value = session.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };
    __size += unknownFields.serializedSize
    __size
  }

  override def serializedSize: _root_.scala.Int = {
    var __size = __serializedSizeMemoized
    if (__size == 0) {
      __size = __computeSerializedSize() + 1
      __serializedSizeMemoized = __size
    }
    __size - 1

  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    session.foreach { __v =>
      val __m = __v
      _output__.writeTag(1, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    };
    unknownFields.writeTo(_output__)
  }

  def getSession: SessionData = session.getOrElse(SessionData.defaultInstance)

  def clearSession: GetSessionResponse = copy(session = _root_.scala.None)

  def withSession(__v: SessionData): GetSessionResponse = copy(session = Option(__v))

  def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet): GetSessionResponse = copy(unknownFields = __v)

  def discardUnknownFields: GetSessionResponse = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 1 => session.orNull
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 1 => session.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
    }
  }

  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion: GetSessionResponse.type = GetSessionResponse

}

object GetSessionResponse extends scalapb.GeneratedMessageCompanion[GetSessionResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[GetSessionResponse] = this

  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): GetSessionResponse = {
    var __session: _root_.scala.Option[SessionData]                 = _root_.scala.None
    var `_unknownFields__` : _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__                                                     = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0   => _done__ = true
        case 10  =>
          __session = Option(
            __session.fold(_root_.scalapb.LiteParser.readMessage[SessionData](_input__))(
              _root_.scalapb.LiteParser.readMessage(_input__, _)
            )
          )
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    GetSessionResponse(
      session = __session,
      unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }

  implicit def messageReads: _root_.scalapb.descriptors.Reads[GetSessionResponse] = _root_.scalapb.descriptors.Reads {
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(
        __fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor),
        "FieldDescriptor does not match message type."
      )
      GetSessionResponse(
        session =
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[SessionData]])
      )
    case _                                                => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    ReplicatedSessionStoreProto.javaDescriptor.getMessageTypes.get(3)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ReplicatedSessionStoreProto.scalaDescriptor.messages(3)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @ _root_.scala.unchecked) match {
      case 1 => __out = SessionData
    }
    __out
  }

  lazy val nestedMessagesCompanions
    : Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] =
    throw new MatchError(__fieldNumber)

  lazy val defaultInstance: GetSessionResponse = GetSessionResponse(session = _root_.scala.None)

  implicit class GetSessionResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, GetSessionResponse])
      extends _root_.scalapb.lenses.ObjectLens[UpperPB, GetSessionResponse](_l) {

    def session: _root_.scalapb.lenses.Lens[UpperPB, SessionData] =
      field(_.getSession)((c_, f_) => c_.copy(session = Option(f_)))

    def optionalSession: _root_.scalapb.lenses.Lens[UpperPB, scala.Option[SessionData]] =
      field(_.session)((c_, f_) => c_.copy(session = f_))

  }

  final val SESSION_FIELD_NUMBER = 1

  def of(session: scala.Option[SessionData]): GetSessionResponse = GetSessionResponse(session)

}

object ReplicatedSessionStoreProto extends _root_.scalapb.GeneratedFileObject {

  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.empty.EmptyProto,
    kalix.AnnotationsProto,
    scalapb.options.ScalapbProto
  )

  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      SessionData,
      SessionKey,
      StoreSessionRequest,
      GetSessionResponse
    )

  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
    scalapb.Encoding.fromBase64(
      scala.collection.immutable
        .Seq(
          """CkFjb20vZXhhbXBsZS9ib3VuZGVkLWNvbnRleHQvZW50aXR5L3JlcGxpY2F0ZWRfc2Vzc2lvbl9zdG9yZS5wcm90bxIiY29tL
  mltcHJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbBobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGhdrYWxpeC9hbm5vdGF0a
  W9ucy5wcm90bxoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIiwKC1Nlc3Npb25EYXRhEh0KBGRhdGEYAiABKAxCCeI/BhIEZGF0YVIEZ
  GF0YSJZCgpTZXNzaW9uS2V5Ei8KCWVudGl0eV9pZBgBIAEoCUIS4j8KEghlbnRpdHlJZMJDAggBUghlbnRpdHlJZBIaCgNrZXkYA
  iABKAlCCOI/BRIDa2V5UgNrZXkigQEKE1N0b3JlU2Vzc2lvblJlcXVlc3QSLwoJZW50aXR5X2lkGAEgASgJQhLiPwoSCGVudGl0e
  UlkwkMCCAFSCGVudGl0eUlkEhoKA2tleRgCIAEoCUII4j8FEgNrZXlSA2tleRIdCgRkYXRhGAMgASgMQgniPwYSBGRhdGFSBGRhd
  GEibQoSR2V0U2Vzc2lvblJlc3BvbnNlElcKB3Nlc3Npb24YASABKAsyLy5jb20uaW1wcm92aW5nLmV4dGVuc2lvbnMub2lkYy5pb
  XBsLlNlc3Npb25EYXRhQgziPwkSB3Nlc3Npb25SB3Nlc3Npb24yjAMKFlJlcGxpY2F0ZWRTZXNzaW9uU3RvcmUSXQoKUHV0U2Vzc
  2lvbhI3LmNvbS5pbXByb3ZpbmcuZXh0ZW5zaW9ucy5vaWRjLmltcGwuU3RvcmVTZXNzaW9uUmVxdWVzdBoWLmdvb2dsZS5wcm90b
  2J1Zi5FbXB0eRJ0CgpHZXRTZXNzaW9uEi4uY29tLmltcHJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbC5TZXNzaW9uS2V5GjYuY
  29tLmltcHJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbC5HZXRTZXNzaW9uUmVzcG9uc2UanAHKQ5gBGpUBCj9jb20uaW1wcm92a
  W5nLmV4dGVuc2lvbnMub2lkYy5pbXBsLlJlcGxpY2F0ZWRTZXNzaW9uU3RvcmVFbnRpdHkSGHJlcGxpY2F0ZWQtc2Vzc2lvbi1zd
  G9yZUI4CgZzdHJpbmcSLmNvbS5pbXByb3ZpbmcuZXh0ZW5zaW9ucy5vaWRjLmltcGwuU2Vzc2lvbkRhdGFCMOI/LQoiY29tLmltc
  HJvdmluZy5leHRlbnNpb25zLm9pZGMuaW1wbBABKAFYALgBAGIGcHJvdG8z"""
        )
        .mkString
    )

  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }

  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(
      javaProto,
      _root_.scala.Array(
        com.google.protobuf.empty.EmptyProto.javaDescriptor,
        kalix.AnnotationsProto.javaDescriptor,
        scalapb.options.ScalapbProto.javaDescriptor
      )
    )
  }

  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor

}
