# DON'T REMOVE THIS FILE.
# This file is for render site varibles and plugins
#
# The actual configuration files are stored in the `config/_default/` folder.

######################### site variables ##############################
# customize your color and font from here.
[params.variables]
black = "#000"
body_color = "#fff"
border_color = "#cccccc"
color_primary = "#2e7eed"
color_secondary = "#fff"
dark = "#222"
text_color = "#808080"
text_dark = "#757575"
text_light = "#fafafa"
white = "#fff"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.20" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_icon = "Font Awesome 6 Free" # https://fontawesome.com/v6/icons
font_primary = "Open+Sans:wght@300;400;500;600;700;800" 
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Lora" 
font_secondary_type = "serif" # [serif/sans-serif]

############################# Plugins ##############################

# CSS Plugins 
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/regular.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper.css"

# JS Plugins
# [[params.plugins.js]]
# link = "plugins/jquery/jquery.js" 
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper.js"
