# Modified from https://github.com/lightbend/kalix-jvm-sdk/blob/main/samples/scala-protobuf-customer-registry-quickstart/docker-compose.yml

services:
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.18
    depends_on:
      - gateway
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dkalix.dev-mode.service-port-mappings.service1=host.docker.internal:9001
        -Dkalix.dev-mode.service-port-mappings.service2=host.docker.internal:9002
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: "8081"

  kalix-proxy-gateway:
    image: gcr.io/kalix-public/kalix-proxy:1.1.18
    depends_on:
      - service1
      - service2
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: "8080"

  gateway:
    image: gateway:latest
    ports:
      - "8080:8080"
    environment:
      HOST: gateway

  service1:
    image: service1:latest
    ports:
      - "8080:8080"
    environment:
      HOST: service1

  service2:
    image: service2:latest
    ports:
      - "8080:8080"
    environment:
      HOST: service2