# Modified from https://github.com/lightbend/kalix-jvm-sdk/blob/main/.github/workflows/ci.yml

name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    name: Basic checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # v3.1.0
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Restore Coursier cache
        # https://github.com/actions/cache/releases
        # v3.3.1
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
            ~/.ivy2/cache
          key: coursier-${{ hashFiles('project/plugins.sbt', 'project/build.properties') }}-${{ hashFiles('build.sbt', 'project/**.scala', 'project/**.sbt') }}
          restore-keys: |
            coursier-${{ hashFiles('project/plugins.sbt', 'project/build.properties') }}-${{ hashFiles('build.sbt', 'project/**.scala', 'project/**.sbt') }}
            coursier-${{ hashFiles('project/plugins.sbt', 'project/build.properties') }}-
            coursier-

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.0
        uses: coursier/setup-action@70323223454ac2a9eb2de46f389b4d045cbcdea5
        with:
          jvm: temurin:1.17

      - name: Run header checks
        run: |
          sbt --client headerCheckAll || \
            { echo "[error] Code missing headers prior to commit. Run 'sbt headerCreateAll' then commit the updated code."; false; }

      - name: Run scalafmt checks
        run: |
          sbt --client "scalafmtCheckAll; scalafmtSbtCheck" || \
            { echo "[error] Code not formatted prior to commit. Run 'sbt scalafmtAll scalafmtSbt' then commit the reformatted code."; false; }

      - name: sbt shutdown
        run: |
          sbt --client shutdown

  build-publish-test:
    name: Build, publish locally, test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # v3.1.0
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        # https://github.com/actions/cache/releases
        # v3.3.1
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
            ~/.ivy2/cache
          key: coursier-${{ hashFiles('project/plugins.sbt', 'project/build.properties') }}-${{ hashFiles('build.sbt', 'project/**.scala', 'project/**.sbt') }}
          restore-keys: |
            coursier-${{ hashFiles('project/plugins.sbt', 'project/build.properties') }}-${{ hashFiles('build.sbt', 'project/**.scala', 'project/**.sbt') }}
            coursier-${{ hashFiles('project/plugins.sbt', 'project/build.properties') }}-
            coursier-

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.0
        uses: coursier/setup-action@70323223454ac2a9eb2de46f389b4d045cbcdea5
        with:
          jvm: temurin:1.17

      - name: Build and publish project
        id: build_sdk
        run: |-
          sbt "Docker / publishLocal"

      - name: sbt test
        run: sbt test
