name: NPM-CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/npm-ci.yml
      - '**.proto'
      - '**.sh'
      - '**.tsx'
      - '**.ts'
      - '**.scss'
      - '**.css'

  push:
    branches:
      - main
    paths:
      - .github/workflows/npm-ci.yml
      - '**.proto'
      - '**.sh'
      - '**.tsx'
      - '**.ts'
      - '**.scss'
      - '**.css'

permissions:
  contents: read

jobs:
  ui-build-test:
    name: npm build, test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: protoGen for scala project
        run: sbt protocGenerate

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "24.x"

      - name: npm
        working-directory: ui
        run: |
          npm install -g protoc-gen-js
          npm ci
          ./proto-gen.sh
          # TODO: enable when tests are ready 
          # npm test
